###
GET http://localhost:3000/users

###
# Create a new user
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "John Doe",
  "userEmail": "ffff",
  "password": "null",
  "admin": ""
}

###
# update a user
###
PUT http://localhost:3000/users/5
Content-Type: application/json

{
  "userName": "sa",
  "userEmail": "sari@gmail.com",
  "admin": 0,
  "password": "haha"
}

###
GET http://localhost:3000/news


###
# Create a new news
###
POST http://localhost:3000/news
Content-Type: application/json

{
  "content": "This is a news",
  "userId": 9
}

###
# update a news
###
PUT http://localhost:3000/news/1
Content-Type: application/json

{
  "content": "This is a new news",
  "userId": 9
}
