###
GET http://localhost:3000/users/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc1OTQ4NTk2LCJleHAiOjE2NzU5NzczOTZ9.1jD_BUgfPZUvuBwOUl7ZAC-wadWa-fZ_L_zKDt0lTb4

###
# Create a new user
###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "userName": "Saroooo",
  "userEmail": "Saroooo@hotmail.com",
  "password": "Saroooossss"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8iLCJpYXQiOjE2NzMyNzgyNTIsImV4cCI6MTY3MzMwNzA1Mn0.dk6-T6q9m7QNYqvedQD9Muolso2pEbPnpljzwsjKKg8

{
  "userEmail": "sara@gmail.com",
  "password": "påpo1234"
}

###
POST http://localhost:3000/users/forgotPassword
Content-Type: application/json

{
  "userEmail": "jonathanengman@hotmail.com"
}

###
PATCH http://localhost:3000/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc1OTMxNDIyLCJleHAiOjE2NzU5NjAyMjJ9.OgGXwFY89o_cfWX5Ezf0Ur5q7ntMs40sXIswmjWgp7c

{
  "id": 20,
  "userName": "test2",
  "userEmail": "test2@gmail.com",
  "password": "123456789",
  "admin": 0
}

###
PATCH http://localhost:3000/users/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc1MTU5MzU5LCJleHAiOjE2NzUxODgxNTl9.lPdyddzWde9NxI5Q-6JvYBYDC03fQodhVz7Wh4RtvSk

{
  "id": 20,
  "softDelete": true
}

### 
DELETE http://localhost:3000/users/delete/63
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc1MTU5MzU5LCJleHAiOjE2NzUxODgxNTl9.lPdyddzWde9NxI5Q-6JvYBYDC03fQodhVz7Wh4RtvSk


###
POST http://localhost:3000/users/changePasswordUser
Content-Type: application/json

{
  "userEmail": "ddddd@gmail.com",
  "newPassword": "1234568884"
}

###
POST http://localhost:3000/users/changePasswordAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3QxIiwiaWF0IjoxNjczMDUxMjA3LCJleHAiOjE2NzMwODAwMDd9.QaEimAzjoPU_V7U3q9-kdGzD6nHCjsosp0dGB_G4IL0

{
  "userEmail": "test1@gmail.com",
  "newPassword": "12384"
}

###
POST http://localhost:3000/users/changeUserEmail
Content-Type: application/json

{
  "id": 20,
  "userEmail": "test2Change@gmail.com",
  "password": "12384",
  "newUserEmail": "test1@gmail.com"
}

###
GET http://localhost:3000/users/checkToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3QxIiwiaWF0IjoxNjczMDQ4MjA3LCJleHAiOjE2NzMwNzcwMDd9.fvqdmY1Y3isw-v0a_9nCijwxN_pkFy2lJn3Q9SohmCU

{
  "userEmail": "test1@gmail.com",
  "password": "test1"
}


###
GET http://localhost:3000/news/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc1Njk0Mzk0LCJleHAiOjE2NzU3MjMxOTR9.0IiiweieD4xd32GFOgvIRIDlj0cZr9qXj2j6fi-VOUU

###
GET http://localhost:3000/news?limit=6

###
# Create a new news
###
POST http://localhost:3000/news/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc1NjEzMTA5LCJleHAiOjE2NzU2NDE5MDl9.LYHz3Wo-ePohGYeySfw-hKUFh1Mk5xwG157wQm9zlEM

{
  "content": "<p>hej</p><h1>Vad gör du idag?</h1>",
  "image" : "https://via.placeholder.com/150",
  "userId": 20
}

# update a news
###
PATCH http://localhost:3000/news/update
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8iLCJpYXQiOjE2NzMyNzcxOTAsImV4cCI6MTY3MzMwNTk5MH0.MueFmYzHwpkbPvYyl1n6VuprYgvLBs4qvIdV901QC6g

{
  "content": "<p>Via: </p><h1>HEAD </h1>",
  "image" : "https://via.placeholder.com/150",
  "userId": 18,
  "id": 6
}

###
# delete a news
###
PATCH http://localhost:3000/news/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8xMjM0IiwiaWF0IjoxNjc0NjQ3MzMwLCJleHAiOjE2NzQ2NzYxMzB9.wW8HtgSrKLCwBxB5Bhw5TpyFdFlAyb8wCGghBcSdYxE

{
  "id": 5,
  "softDelete": 1
}


###

DELETE http://localhost:3000/news/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJzYXJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicMOlcG8iLCJpYXQiOjE2NzMyNzcxOTAsImV4cCI6MTY3MzMwNTk5MH0.MueFmYzHwpkbPvYyl1n6VuprYgvLBs4qvIdV901QC6g

{
  "id": 5,
  "softDelete": 1
}
# mysql://ba4d586f28e3e3:76641af4@eu-cdbr-west-03.cleardb.net/heroku_d08c491a2b637ff?reconnect=true